# docker-compose.yml

version: '3.8'

services:
  telegram-bot:
    # Dockerfile ko use karke image banayega
    build: .
    # Container ka naam
    container_name: pyrogram_bot
    # Restart policy: Agar bot crash ho, to khud hi restart ho jaye
    restart: always
    # Environment variables (secrets) yahan define karte hain local testing ke liye
    # Deployment par yeh platform ke Config Vars se aayenge
    environment:
      # Apne config.py ke variables yahan set karein
      - API_ID=123456
      - API_HASH=your_api_hash
      - BOT_TOKEN=your_bot_token
      - DB_URI=mongodb_uri_link
      - CHANNEL_LINK=https://t.me/channel
      - OWNER_LINK=https://t.me/owner
    # Volume: Agar aap chahe to local files ko container se sync kar sakte hain
    # volumes:
    #   - .:/app
